project: subsonic
project_dir: "/home/staccato/staccato/evaluation/subsonic"
test: "/home/staccato/staccato/evaluation/subsonic/ss_test2.jmx"
havoc: "/home/staccato/staccato/evaluation/subsonic/ss_havoc.jmx"
test_impl: "JMeterTest"
havoc_iter: 75
test_iter: 150
