project: jforum
project_dir: "/home/staccato/staccato/evaluation/jforum"
test: "/home/staccato/staccato/evaluation/jforum/forum_test.jmx"
havoc: "/home/staccato/staccato/evaluation/jforum/forum_havoc.jmx"
test_impl: "JMeterTest"
havoc_iter: 75
test_iter: 100
